name: 'Generate artifacts'
description: 'Generating artifacts according changes'
inputs:
  artifact:
    required: true
runs:
  using: "composite" 
  steps:
    - name: Checkout
      shell: bash
      uses: actions/checkout@v2.1.0
    - name: Generate artifacts
      shell: bash
      run: |
        if [ "${{ artifact.tool }}" != "builder.sh" ]; then
          bash unattended_installer/builder.sh --${{ artifact.tool }}
        fi
