name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3', 'master' ]

jobs:
  get-file-changes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.0
      - name: get files
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.changed_files.outputs.all }}"
      - name: Display changed files cert_tool
        id: modified_files_list
        if: contains(steps.changed_files.outputs.all, 'cert_tool')
        run: |
          echo ::set-output name=arch::$(echo 'cert-tool')
          echo "yes"
