name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3', 'master' ]

jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Get Files
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tools file
        run: echo "[" > tools.json
      - name: Display changed files cert_tool
        id: cert-tool
        if: contains(steps.changed_files.outputs.all, 'cert_tool')
        run: echo '{\"tool\":\"cert-tool\"}' >> tools.json
      - name: Display changed files passwords_tool
        id: changed-file
        if: contains(steps.changed_files.outputs.all, 'passwords_tool')
        run: echo ',{\"tool\":\"passwords-tool\"}' >> tools.json
      - name: Finish file
        run: echo "]" >> tools.json
      - name: Build Matrix
        id: set-matrix
        run: echo '''::set-output name=tools_matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}'''
      - name: cat json
        run: echo ${{ steps.set-matrix.outputs.tools_matrix }}
    outputs:
      tools_matrix: ${{ steps.set-matrix.outputs.tools_matrix }}
  
  job2:
    needs: get-files
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        tools: ${{ fromJson({\"data\":[{\"tool\":\"cert-tool\"},{\"tool\":\"passwords-tool\"}]}) }}
    steps:
      - name: builder-sh
        run: echo ${{ matrix.tools }}
  
  Builder-Scripts:
    runs-on: ubuntu-latest
    needs: get-files
    strategy:
      matrix:
        tools: ${{fromJson(needs.build-matrix.outputs.tools_matrix)}}
    steps:
      - name: builder-sh
        run: echo ${{ matrix.tools }}
  
