name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3', 'master' ]

jobs:
  get-files:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.cert-tool.outputs.param }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Get Files
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "${{ steps.changed_files.outputs.all }}"
      - name: Display changed files cert_tool
        id: cert-tool
        if: contains(steps.changed_files.outputs.all, 'cert_tool')
        run: echo "::set-output name=param::cert-tool"
      - name: Display changed files password_tool
        id: changed-file
        if: contains(steps.changed_files.outputs.all, 'password_tool')
        run: echo "::set-output name=param::param+password-tool"
          
  Builder-Scripts:
    runs-on: ubuntu-latest
    needs: get-files
    steps:
      - name: builder-sh
        run: echo ${{ needs.get-files.outputs.file }}
  
