name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3', 'master' ]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.step1.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Get Files
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "${{ steps.changed_files.outputs.all }}"
      - name: Display changed files cert_tool
        id: step1
        if: contains(steps.changed_files.outputs.all, 'cert_tool')
        run: echo "::set-output name=test::cert-tool"
          
  Builder-Scripts:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: builder-sh
        run: echo ${{ needs.job1.outputs.file }}
  
