name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3', 'master' ]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TASKS=$(echo $(["cert-tool","passwords-tool"]) | sed 's/ //g' )
          echo "::set-output name=matrix::$TASKS"
  builder:
    runs-on: ubuntu-latest
    needs: [ matrix ]
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: builder-sh
        run: echo ${{ matrix.cfg }}
  
