name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3' ]
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: shellcheck-github-pr-review
        uses: ./unattended_installer/
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: '*.sh'
          path: './unattended_installer'
          exclude: './unattended_installer/Development-guide.md'
