name: pr-review
on: 
  pull_request:
    branches: [ 'poc-shellcheck-to4.3', 'master' ]

jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Get Files
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tools file
        run: echo "" > tools.csv
      - name: Display changed files cert_tool
        id: cert-tool
        if: contains(steps.changed_files.outputs.all, 'cert_tool')
        run: echo " cert-tool" >> tools.csv
      - name: Display changed files passwords_tool
        id: changed-file
        if: contains(steps.changed_files.outputs.all, 'passwords_tool')
        run: echo " passwords-tool" >> tools.csv
      - name: cat tools
        run: cat tools.csv

  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "::set-output name=tools_matrix::$(cat tools.csv | tr " " ",")"
    outputs:
      tools_matrix: ${{ steps.set-matrix.outputs.tools_matrix }}
  
  Builder-Scripts:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix:
        tools: ${{ fromJson(needs.build-matrix.outputs.tools_matrix) }}
    steps:
      - name: builder-sh
        run: echo ${{ matrix.tools }}
  
