name: Shellcheck code analysis
on: [pull_request]

jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Get changes
        uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: space-delimited
      - name: Set tools
        uses: './.github/actions/get-tools/'
        with: 
          tool: "${{ steps.changed_files.outputs.all }}"
      - name: Build matrix
        id: set-matrix
        run: |
          echo "::set-output name=tools_matrix::[${{ env.VAR }}]"
    outputs:
      tools_matrix: ${{ steps.set-matrix.outputs.tools_matrix }}
  
  Builder-Scripts:
    runs-on: ubuntu-latest
    needs: get-artifacts
    strategy:
      matrix: 
        tool: ${{ fromJson(needs.get-artifacts.outputs.tools_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Generate artifacts
        uses: './.github/actions/generate-artifacts/'
        with: 
          artifact: "${{ matrix.tool }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_generated
          path: |
            unattended_installer/**tool.sh
          
  Shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    needs: Builder-Scripts
    steps:
      - uses: actions/checkout@v1
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Shellcheck for libraries of artifacts
        uses: './.github/actions/shellcheck/'
        with:
          reporter: github-check
          path: "./artifacts_generated"
          pattern: "*.sh"
          fail_on_error: "false"
      - name: Shellcheck for artifacts generated
        uses: './.github/actions/shellcheck/'
        with:
          reporter: github-pr-review
          path: "./artifacts_generated"
          pattern: "*.sh"
          fail_on_error: "false"
      - name: Comments into issue
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
